server:
  port: 9000
spring:
  redis:
    database: 0
    host: 118.190.69.246
    password: midu_ahd
    port: 6379
  datasource:
    username: pdream
    password: pdream-group
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.190.69.246:3306/test?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
  messages:
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
  thymeleaf:
    cache: false
  activemq:
    broker-url: tcp://114.67.231.108:61616
    user: admin
    password: pdream_group
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: input
shiro:
  loginUrl: /
