server:
  port: 8080
spring:
  redis:
    database: 0
    host: 118.190.69.246
    password: midu_ahd
    port: 6379
  messages:
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
  thymeleaf:
      cache: false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: input