spring:
  profiles:
    active: dev
  messages:
    encoding: utf-8
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: input
shiro:
  loginUrl: /
