server:
  port: 8081
spring:
  redis:
    database: 0
    host: 118.190.69.246
    password: midu_ahd
    port: 6379
  datasource:
    username: pdream
    password: pdream-group
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://118.190.69.246:3306/test?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
  thymeleaf:
    cache: true
  activemq:
    broker-url: tcp://114.67.231.108:61616
    user: admin
    password: pdream_group