spring:
  profiles:
    active: dev
  messages:
    encoding: utf-8
  http:
    encoding:
      charset: UTF-8
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: input
shiro:
  loginUrl: /

server:
  ssl:
    key-store-password: 123456
    key-alias: tomcathttps
    key-store: javaboy.p12
