server:
  port: 8080
spring:
  redis:
    database: 0
    host: 118.190.69.246
    password: midu_ahd
    port: 6379
    # 配置了这个，才会用到池
    lettuce:
      pool:
        max-active: 8
        #连接池最大阻塞等待时间毫秒(使用负值表示没有限制-1ms)
        max-wait: 6000ms
        min-idle: 1
        max-idle: 8
    timeout: 2000ms
  datasource:
    username: pdream
    password: pdream-group
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://118.190.69.246:3306/test?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    hikari:
      minimum-idle: 2
      #      连接池最大连接数，默认是10
      maximum-pool-size: 7
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      #       此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
  thymeleaf:
    cache: false
  activemq:
    broker-url: tcp://114.67.231.108:61616
    user: admin
    password: pdream_group

